apiVersion: apps/v1
kind: Deployment
metadata:
  name: pydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pydeploy
  template:
    metadata:
      labels:
        app: pydeploy
    spec:
      containers:
        - name: pydeploy
          image: jitender12/pydeploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000